# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-03 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infectiousdiseases', '0004_auto_20170207_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalliaisoncontactdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_infectiousdiseases_externalliaisoncontactdetails_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='externalliaisoncontactdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_infectiousdiseases_externalliaisoncontactdetails_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
