# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0034_auto_20171214_1845'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infectiousdiseases', '0005_auto_20180303_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiaisonOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('phone_advice_given', models.BooleanField(default=False)),
                ('redirected_to_clinic', models.CharField(blank=True, choices=[(b'OPAT', b'OPAT'), (b'RAID', b'RAID'), (b'Walk-in', b'Walk-in')], max_length=256, null=True)),
                ('email_advice_given', models.BooleanField(default=False)),
                ('transfer_offered', models.BooleanField(default=False)),
                ('transfer_response', models.CharField(blank=True, choices=[(b'Declined', b'Declined'), (b'Accepted', b'Accepted')], max_length=256, null=True)),
                ('liaison_ended', models.NullBooleanField()),
                ('next_date_of_contact', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_infectiousdiseases_liaisonoutcome_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_infectiousdiseases_liaisonoutcome_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
