# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infectiousdiseases', '0006_liaisonoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiaisonProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='liaisonoutcome',
            name='problem_category_ft',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liaisonoutcome',
            name='problem_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infectiousdiseases.LiaisonProblem'),
        ),
    ]
