# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-17 19:22
from __future__ import unicode_literals

from django.db import migrations

PATIENT_OUTCOME_MAPPING = dict(
    Cure='Cured',
    Improved='Improved',
    Failure='Failed'
)

OPAT_OUTCOME_MAPPING = {
    'Success': 'Success',
    'Partial Success': 'Parcial',
    'Failure of OPAT': 'Failed',
    'Intermidiate Outcome': 'Undeterminate'
}


def forward(apps, *args):
    OPATOutcome = apps.get_model('opat', 'OPATOutcome')
    for i, v in PATIENT_OUTCOME_MAPPING.items():
        OPATOutcome.objects.filter(
            patient_outcome=i
        ).update(
            patient_outcome=v
        )
    for i, v in OPAT_OUTCOME_MAPPING.items():
        OPATOutcome.objects.filter(
            opat_outcome=i
        ).update(
            opat_outcome=v
        )


def backwards(apps, *args):
    OPATOutcome = apps.get_model('opat', 'OPATOutcome')
    for i, v in PATIENT_OUTCOME_MAPPING.items():
        OPATOutcome.objects.filter(
            patient_outcome=v
        ).update(
            patient_outcome=i
        )
    for i, v in OPAT_OUTCOME_MAPPING.items():
        OPATOutcome.objects.filter(
            opat_outcome=v
        ).update(
            opat_outcome=i
        )


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0007_auto_20180303_1431'),
    ]

    operations = [
        migrations.RunPython(forward, reverse_code=backwards)
    ]
