# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0008_opat_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opatoutcome',
            name='opat_outcome',
            field=models.CharField(blank=True, choices=[(b'Success', b'Success'), (b'Parcial', b'Parcial'), (b'Failed', b'Failed'), (b'Undeterminate', b'Undeterminate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='opatoutcome',
            name='patient_outcome',
            field=models.CharField(blank=True, choices=[(b'Cured', b'Cured'), (b'Improved', b'Improved'), (b'Failed', b'Failed')], max_length=200, null=True),
        ),
    ]
