# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0001_initial'),
        ('elcid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='destination_fk',
            field=models.ForeignKey(blank=True, to='opal.Destination', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='travel',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='travel',
            name='malaria_drug_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='travel',
            name='reason_for_travel_fk',
            field=models.ForeignKey(blank=True, to='opal.Travel_reason', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='todo',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='secondarydiagnosis',
            name='condition_fk',
            field=models.ForeignKey(blank=True, to='opal.Condition', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='secondarydiagnosis',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='ridrtitest',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='primarydiagnosis',
            name='condition_fk',
            field=models.ForeignKey(blank=True, to='opal.Condition', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='primarydiagnosis',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='presentingcomplaint',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='presentingcomplaint',
            name='symptom_fk',
            field=models.ForeignKey(blank=True, to='opal.Symptom', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pastmedicalhistory',
            name='condition_fk',
            field=models.ForeignKey(blank=True, to='opal.Condition', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='pastmedicalhistory',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatreview',
            name='adverse_events_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial_adverse_event', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatreview',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatreview',
            name='rv_type_fk',
            field=models.ForeignKey(blank=True, to='elcid.Opat_rvt', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatrejection',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatoutstandingissues',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatoutcome',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatmeta',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatmeta',
            name='unplanned_stop_reason_fk',
            field=models.ForeignKey(blank=True, to='elcid.Unplanned_stop', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='opatlineassessment',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='microbiologytest',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='microbiologytest',
            name='hiv_declined_fk',
            field=models.ForeignKey(blank=True, to='elcid.Hiv_no', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='microbiologyinput',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='microbiologyinput',
            name='reason_for_interaction_fk',
            field=models.ForeignKey(blank=True, to='opal.Clinical_advice_reason_for_interaction', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='location',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='line',
            name='complications_fk',
            field=models.ForeignKey(blank=True, to='opal.Line_complication', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='line',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='line',
            name='line_type_fk',
            field=models.ForeignKey(blank=True, to='opal.Line_type', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='line',
            name='removal_reason_fk',
            field=models.ForeignKey(blank=True, to='opal.Line_removal_reason', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='line',
            name='site_fk',
            field=models.ForeignKey(blank=True, to='opal.Line_site', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labtest',
            name='antimicrobials_intermediate_fk',
            field=models.ForeignKey(related_name=b'intermediate', blank=True, to='elcid.Antimicrobial_susceptability', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labtest',
            name='antimicrobials_resistant_fk',
            field=models.ForeignKey(related_name=b'resistant', blank=True, to='elcid.Antimicrobial_susceptability', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labtest',
            name='antimicrobials_susceptible_fk',
            field=models.ForeignKey(related_name=b'susceptible', blank=True, to='elcid.Antimicrobial_susceptability', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labtest',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labtest',
            name='organism_details_fk',
            field=models.ForeignKey(blank=True, to='elcid.Organism_details', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labspecimin',
            name='appearance_fk',
            field=models.ForeignKey(blank=True, to='elcid.Specimin_appearance', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labspecimin',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labspecimin',
            name='specimin_type_fk',
            field=models.ForeignKey(blank=True, to='elcid.Specimin', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='generalnote',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='condition_fk',
            field=models.ForeignKey(blank=True, to='opal.Condition', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demographics',
            name='country_of_birth_fk',
            field=models.ForeignKey(blank=True, to='opal.Destination', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='demographics',
            name='patient',
            field=models.ForeignKey(to='opal.Patient'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='patient',
            field=models.ForeignKey(to='opal.Patient'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='checkpointsassay',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carers',
            name='gp',
            field=models.ForeignKey(blank=True, to='opal.GP', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carers',
            name='nurse',
            field=models.ForeignKey(blank=True, to='opal.CommunityNurse', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='carers',
            name='patient',
            field=models.ForeignKey(to='opal.Patient'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='appointment',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='adverse_event_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial_adverse_event', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='delivered_by_fk',
            field=models.ForeignKey(blank=True, to='elcid.Drug_delivered', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='drug_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='episode',
            field=models.ForeignKey(to='opal.Episode'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='frequency_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial_frequency', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='reason_for_stopping_fk',
            field=models.ForeignKey(blank=True, to='elcid.Iv_stop', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='antimicrobial',
            name='route_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial_route', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='allergies',
            name='drug_fk',
            field=models.ForeignKey(blank=True, to='opal.Antimicrobial', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='allergies',
            name='patient',
            field=models.ForeignKey(to='opal.Patient'),
            preserve_default=True,
        ),
    ]
