# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-03 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0056_auto_20171226_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbiologytest',
            name='rhinovirus',
            field=models.CharField(blank=True, choices=[(b'pending', b'pending'), (b'positive', b'positive'), (b'negative', b'negative')], max_length=20),
        ),
    ]
