# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0057_microbiologytest_rhinovirus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[(b'DoctorClinic', b'Doctor Clinic review appointment'), (b'NurseClinic', b'Nurse Clinic review appointment')], max_length=200, null=True),
        ),
    ]
