# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0058_auto_20180326_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[(b'Doctor Clinic review appointment', b'Doctor Clinic review appointment'), (b'Nurse Clinic review appointment', b'Nurse Clinic review appointment')], max_length=200, null=True),
        ),
    ]
