# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 09:55
from __future__ import unicode_literals

from django.db import migrations
from elcid.migrations.utils.migrate_symptoms import migrate_forwards


def migrate_backwards(*args, **kwargs):
    """
        an empty function to allow use to migrate backwards, even
        though we don't have to do anything
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0058_auto_20180326_1801'),
    ]

    operations = [
        migrations.RunPython(
            migrate_forwards, reverse_code=migrate_backwards
        )
    ]
