# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0058_auto_20180326_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentingcomplaint',
            name='onset',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
