# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-03 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microhaem', '0002_migrate_content_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeofneutropenia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_microhaem_episodeofneutropenia_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episodeofneutropenia',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_microhaem_episodeofneutropenia_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='haeminformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_microhaem_haeminformation_subrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='haeminformation',
            name='patient_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microhaem.HaemInformationType'),
        ),
        migrations.AlterField(
            model_name='haeminformation',
            name='type_of_chemotherapy_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microhaem.HaemChemotherapyType'),
        ),
        migrations.AlterField(
            model_name='haeminformation',
            name='type_of_transplant_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='microhaem.HaemTransplantType'),
        ),
        migrations.AlterField(
            model_name='haeminformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_microhaem_haeminformation_subrecords', to=settings.AUTH_USER_MODEL),
        ),
    ]
